# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
