# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_count',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
