# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bse', '0002_auto_20171127_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_type', models.IntegerField(verbose_name='ID类型')),
                ('id_number', models.CharField(max_length=30)),
                ('photo1', models.CharField(max_length=50)),
                ('photo2', models.CharField(max_length=50)),
                ('photo3', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_kyc',
            field=models.IntegerField(default=0, verbose_name='key验证'),
        ),
    ]
